ibkr:
  name: IBKR
  category: Misc
  versions: [1.0.2]
  platform: [all]
  repository: homiodev/addon-ibkr
mediamtx:
  name: MediaMTX
  category: Media
  versions: [1.0.0]
  platform: [all]
  repository: homiodev/addon-mediamtx
gdrive:
  name: Google drive
  category: Storage
  versions: [1.0.1]
  platform: [all]
  repository: homiodev/addon-gdrive
dropbox:
  name: Dropbox
  description: Dropbox storage
  category: Storage
  versions: [1.0.3]
  platform: [all]
  repository: homiodev/addon-dropbox
firmata:
  name: Firmata
  description: Firmata bundle to communicate with firmata protocol on arduino, etc...
  category: Microcontrollers
  versions: [1.0.2]
  platform: [win,linux-64,linux-aarch64]
  repository: homiodev/addon-firmata
gcloud_tts:
  name: GoogleCloud Text-to-Speech
  category: Communication
  versions: [1.0.2]
  platform: [all]
  repository: homiodev/addon-gcloud_tts
gpio:
  name: Gpio
  category: Microcontrollers
  versions: [1.0.2]
  platform: [all]
  repository: homiodev/addon-gpio
influxdb:
  name: InfluxDB
  description: Influx DB bundle to store time-series variables to local/cloud databases
  category: Storage
  versions: [1.0.2]
  platform: [all]
  repository: homiodev/addon-influxdb
ipscanner:
  name: Angry Ip Scanner
  category: Tools
  versions: [1.0.4]
  platform: [all]
  repository: homiodev/addon-ipscanner
mail:
  name: Mail
  description: Access POP3, IMAP and SMTP servers.
  category: Communication
  versions: [1.0.4]
  platform: [all]
  repository: homiodev/addon-mail
mongodb:
  name: MongoDB
  category: Storage
  versions: [1.0.1]
  platform: [all]
  repository: homiodev/addon-mongodb
rabbitmq:
  name: RabbitMQ client
  category: Storage
  versions: [1.0.1]
  platform: [all]
  repository: homiodev/addon-rabbitmq
serial:
  name: Serial
  description: Serial bundle for usb/com port usage
  category: Communication
  versions: [1.0.2]
  platform: [all]
  repository: homiodev/addon-serial
weather:
  name: OpenWeather
  description: OpenWeather widget/provider
  category: Tools
  versions: [1.1.0]
  platform: [all]
  repository: homiodev/addon-openweathermap
rf433:
  name: RF433
  category: Tools
  repository: homiodev/addon-rf433
tuya:
  name: Tuya
  description: Tuya wifi device support
  category: Microcontrollers
  versions: [1.0.1]
  platform: [all]
  repository: homiodev/addon-tuya
imou:
  name: Imou
  description: Imou cloud devices support
  category: Microcontrollers
  versions: [1.0.1]  
  platform: [all]
  repository: homiodev/addon-imou
tasmota:
  name: Tasmota
  description: Tasmota support(beta)
  category: Microcontrollers
  versions: [1.0.2]
  tags: [beta]
  platform: [all]
  repository: homiodev/addon-tasmota
esphome:
  name: ESPHome
  description: ESPHome support(beta)
  category: Microcontrollers
  versions: [1.0.1]
  platform: [all]
  tags: [beta]
  repository: homiodev/addon-esphome
